server:
  port: ${SPRING_SERVER_PORT:8085}
spring:
  banner:
    image:
      location:
        /images/banner.png
proxy:
  selenium:
    url: ${SELENIUM_SERVER_URL:http://localhost:4444/wd/hub}
  appium:
    url: ${APPIUM_SERVER_URL:http://localhost:4723/wd/hub}
  healenium:
    container:
      url: ${HEALENIUM_SERVICE:http://localhost:7878}
    server:
      url: ${HEALENIUM_SERVER_URL:http://localhost:7878}
  imitate:
    container:
      url: ${IMITATE_SERVICE:http://localhost:8000}
healing:
  healenabled: ${HEAL_ENABLED:true}
  recoverytries: ${RECOVERY_TRIES:1}
  scorecap: ${SCORE_CAP:.6}