server:
  port: ${SPRING_SERVER_PORT:8085}
spring:
  banner:
    image:
      location:
        /images/banner.png
proxy:
  selenium:
    url: ${SELENIUM_SERVER_URL:http://localhost:4444/wd/hub}
  appium:
    url: ${APPIUM_SERVER_URL:http://localhost:4723/wd/hub}
  healenium:
    container:
      url: ${HEALENIUM_SERVICE:http://localhost:7878}
    server:
      url: ${HEALENIUM_SERVER_URL:http://localhost:7878}
  imitate:
    container:
      url: ${IMITATE_SERVICE:http://localhost:8000}
healing:
  healenabled: ${HEAL_ENABLED:true}
  recoverytries: ${RECOVERY_TRIES:1}
  scorecap: ${SCORE_CAP:.6}
logging:
  level:
    ROOT: ${SPRING_LOG_LEVEL:INFO}
    org.springframework: INFO
    org.mongodb.driver.connection: WARN
    healenium: ${HLM_LOG_LEVEL:debug}
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS,Europe/Moscow} %clr(%5p) %clr(${PID:- }){magenta} %clr(-){faint} %clr([%11.11t]){faint} %clr(%-32.32logger{30}){cyan} %clr(:){faint} %replace(%m){''[\n\r]'',''\\n ''} %replace(%ex){''[\r\n]'', ''\\n ''}%nopex%n'


